version: "3"
services:
  openresty:
    container_name: base_nginx
    image: base/nginx-stable
    ports:
          - "80:80"
    depends_on:
          - php-fpm
    volumes:
          - "./nginx/conf:/usr/local/openresty/nginx/conf"
          - "../log:/var/log"
          - "/data/www:/usr/local/www"
          - "phpsocket:/var/run/php"
  php-fpm:
      container_name: base_php71
      image: base/php-71
      network_mode: "host"
      ports:
          - "9000:9000"
      volumes:
          - "/data/www:/usr/local/www"
          - "./php/etc/php/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
          - "./php/etc/php/conf.d/zz-php.ini:/usr/local/etc/php/conf.d/zz-php.ini"
          - "phpsocket:/var/run/php"
volumes:
    phpsocket: